# Generated by Django 4.2.4 on 2024-05-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=30)),
                ('edu_type', models.CharField(max_length=30)),
                ('edu_unvi', models.CharField(max_length=40)),
                ('edu_yr', models.CharField(max_length=4)),
                ('edu_per', models.CharField(max_length=2)),
            ],
        ),
    ]
