# Generated by Django 4.2.4 on 2024-05-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='edu_per',
            field=models.CharField(max_length=5),
        ),
    ]
