# Generated by Django 4.2.4 on 2024-05-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_education_edu_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='edu_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_unvi',
            field=models.TextField(),
        ),
    ]
