# Generated by Django 4.2.4 on 2024-05-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_education_edu_name_alter_education_edu_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30)),
                ('pro_dis', models.TextField()),
                ('pro_link', models.TextField()),
                ('pro_tech', models.TextField()),
            ],
        ),
    ]
