# Generated by Django 4.2.4 on 2024-05-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_project_pro_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_dis',
            field=models.TextField(max_length=230),
        ),
    ]
