# Generated by Django 4.2.4 on 2024-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_project_pro_dis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30)),
                ('comp_name', models.CharField(max_length=30)),
                ('skill_name', models.TextField()),
                ('about_role', models.TextField(max_length=230)),
            ],
        ),
    ]
